export const UPDATE_CHAT = "UPDATE_CHAT";
export const UPDATE_CHAT_MESSAGES = "UPDATE_CHAT_MESSAGES";
export const SET_CHATROOM = "SET_CHATROOM";
export const SET_CHATROOM_USERS = "SET_CHATROOM_USERS";
export const SET_CHATROOMS = "SET_CHATROOMS";
